### ISSUE TITLE
Model download link not working

### ISSUE THREAD

**Issue by ericliuche** [black-puppydog/PytorchWCT#1]
I tried downloading the model at http://pascal.inrialpes.fr/data2/archetypal_style/models_pytorch.zip but the link seems to be broken. Thanks for your work on this repo!

**Comment by black-puppydog** [comment]
Sorry, I rebuilt that website lately and forgot to include the models again. They're back. Thank you for the hint. :)

**Comment by yaohengzhi** [comment]
Model download link not working, again

**Comment by black-puppydog** [comment]
Hi @yaohengzhi, thanks for raising this.
I just retrieved the models files from an old backup and pushed a new commit that simply puts the models into the git tree. The pascal server form my old team may be gone indefinitely (not sure yet) so it can't really be relied on long-term anyhow.
It's not an elegant solution but I haven't been working on this for multiple years now and this is about as much effort as I can put into it for now. But the files are just ~120MB so it's not _that_ terrible I hope.

While I'm at it: I haven't run this code in ages, so be aware it may be entirely broken by now. After all, this repo was originally created to get it to work with Pytorch 1.0, that's pretty old!

Good luck, and let me know if this still works if you do attempt it. :P
